### ISSUE TITLE
Can you pull a request under the official MobileSAM project?

### ISSUE THREAD

**Issue by ChaoningZhang** [akbartus/MobileSAM-in-the-Browser#1]
Thanks for your interest in  [MobileSAM](https://github.com/ChaoningZhang/MobileSAM), for which I am the first author. 

You did great work! we have already made a demo on the hugging face and are currently building the official demo of [MobileSAM](https://github.com/ChaoningZhang/MobileSAM) as the original SAM. The official demo will kindly resemble what you have done in terms of the concept "MobileSAM in the browser", but it should be much more professional (somewhat like the original segment anything demo). Please kindly let us know whether you are willing to help with this process. Before the official version comes out, we can temporarily use your current version, which is already non-trivial progress. 

Thanks again for your interest in our work.

**Comment by akbartus** [comment]
Thank you for your kind reply. If you are already working on this, I think there is no need to include this example. It was just a small example to show the work of the model on the browser. And I believe full example like in original SAM will be more beneficial.

**Comment by ChaoningZhang** [comment]
> 

Thanks for your great effort. We have already acknowledged your effort in the readme file. Indeed, we are currently working on an official one. We are more like AI researchers instead of developers. Therefore, it would be very helpful, if someone like you can provide help. Your effort is very much appreciated!!!

**Comment by akbartus** [comment]
Thank you.
