### ISSUE TITLE
no encoder.onnx

### ISSUE THREAD

**Issue by nachoXXL** [akbartus/MobileSAM-in-the-Browser#2]
models/mobilesam.encoder.onnx does not exist

models/mobilesam.decoder.onnx does

js uses the non-existing encoder file.

**Comment by akbartus** [comment]
NachoXXL thank you for your notification. I checked the URL and it is indeed present. Please download from this URL: https://cdn.glitch.me/1bd71fd8-ee70-4d58-9594-6680f5fcdc3b/mobilesam.encoder.onnx?v=1688159510030 and let me know if you were able to download it.

**Comment by nachoXXL** [comment]
Hi Akbar,
Solved 👍
Nacho
